pub fn red()     -> string { return string::from("\x1b[31m") }
pub fn green()   -> string { return string::from("\x1b[32m") }
pub fn yellow()  -> string { return string::from("\x1b[33m") }
pub fn blue()    -> string { return string::from("\x1b[34m") }
pub fn cyan()    -> string { return string::from("\x1b[36m") }
pub fn bold()    -> string { return string::from("\x1b[1m") }
pub fn dim()     -> string { return string::from("\x1b[2m") }
pub fn reset()   -> string { return string::from("\x1b[0m") }
