import std/io::{print, println, stdin}

pub fn confirm(question: string) -> bool {
    print(cede question)
    print(string::from(" [Y/n] "))
    auto result = stdin().read_line()
    auto answer = result.unwrap()
    
    // Check first char
    auto raw = string::from(answer.c_str())
    auto first = raw.c_str()
    
    // Simple check: empty or Y/y = true
    if first == "" { return true }
    if first == "Y" { return true }
    if first == "y" { return true }
    return false
}
